In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("E:/ACTE/Data Analyst MAR 2026/Project/Project 1/pizza_sales.csv")

In [3]:
df

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,01-01-2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,01-01-2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,01-01-2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,01-01-2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,01-01-2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,31-12-2015,21:23:10,16.75,16.75,M,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",The Chicken Alfredo Pizza
48616,48617,21348,four_cheese_l,1,31-12-2015,21:23:10,17.95,17.95,L,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",The Four Cheese Pizza
48617,48618,21348,napolitana_s,1,31-12-2015,21:23:10,12.00,12.00,S,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",The Napolitana Pizza
48618,48619,21349,mexicana_l,1,31-12-2015,22:09:54,20.25,20.25,L,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
48619,48620,21350,bbq_ckn_s,1,31-12-2015,23:02:05,12.75,12.75,S,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  int64
 1   order_id           48620 non-null  int64
 2   pizza_name_id      48620 non-null  object
 3   quantity           48620 non-null  int64
 4   order_date         48620 non-null  datetime64[ns]
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  object
 9   pizza_category     48620 non-null  object
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(3), object(6)
memory usage: 4.5+ MB

In [24]:
df.describe()

           pizza_id      order_id      quantity    unit_price   total_price
count  48620.000000  48620.000000  48620.000000  48620.000000  48620.000000
mean   24310.500000  10701.479761      1.019622     16.494132     16.821474
std    14035.529381   6180.119770      0.143077      3.621789      4.437398
min        1.000000      1.000000      1.000000      9.750000      9.750000
25%    12155.750000   5337.000000      1.000000     12.750000     12.750000
50%    24310.500000  10682.500000      1.000000     16.500000     16.500000
75%    36465.250000  16100.000000      1.000000     20.250000     20.500000
max    48620.000000  21350.000000      4.000000     35.950000     83.000000

# Finding Total Revenue

In [25]:
df_total_rev = df['total_price'].sum()
df_total_rev

817860.05

# Finding Total Pizza Sold

In [26]:
df['quantity'].sum()

49574

In [17]:
df['order_date'].astype

<bound method NDFrame.astype of 0       2015-01-01
1       2015-01-01
2       2015-01-01
3       2015-01-01
4       2015-01-01
           ...
48615   2015-12-31
48616   2015-12-31
48617   2015-12-31
48618   2015-12-31
48619   2015-12-31
Name: order_date, Length: 48620, dtype: datetime64[ns]>

In [4]:
df['order_date'] = pd.to_datetime(df['order_date'],format='%d-%m-%Y')

In [28]:
Month_name = df['order_date'].dt.month_name()
Month_name

0         January
1         January
2         January
3         January
4         January
           ...
48615    December
48616    December
48617    December
48618    December
48619    December
Name: order_date, Length: 48620, dtype: object

In [29]:
df['order_date'].dt.strftime('%b')

0        Jan
1        Jan
2        Jan
3        Jan
4        Jan
        ...
48615    Dec
48616    Dec
48617    Dec
48618    Dec
48619    Dec
Name: order_date, Length: 48620, dtype: object

In [30]:
df.columns

Index(['pizza_id', 'order_id', 'pizza_name_id', 'quantity', 'order_date',
       'order_time', 'unit_price', 'total_price', 'pizza_size',
       'pizza_category', 'pizza_ingredients', 'pizza_name'],
      dtype='object')

In [7]:
df['order_id']

0            1
1            2
2            2
3            2
4            2
         ...
48615    21348
48616    21348
48617    21348
48618    21349
48619    21350
Name: order_id, Length: 48620, dtype: int64

In [31]:
df_unq_ord = df['order_id'].nunique()
df_unq_ord

21350

# Find Average Order Value

In [32]:
avg_order_pervalue = df_total_rev/df_unq_ord

In [33]:
avg_order_pervalue

38.30726229508197

In [34]:
817860.05/21350

38.30726229508197

# Finding Total Order

In [14]:
df['order_id'].nunique()

21350

In [35]:
 df['quantity'].sum()

49574

In [36]:
49574/21350

2.321967213114754

# Avg Pizza per order

In [15]:
avg_pizzas_per_order = round(
    df['quantity'].sum() / df['order_id'].nunique(), 2
)

print(avg_pizzas_per_order)

2.32

# Day Trend for Total Orders

In [20]:
# df['order_date'] = pd.to_datetime(df['order_date'])

result = (
    df.groupby(df['order_date'].dt.day_name())['order_id']
      .nunique()
      .reset_index(name='total_orders')    
)

print(result)

  order_date  total_orders
0     Friday          3538
1     Monday          2794
2   Saturday          3158
3     Sunday          2624
4   Thursday          3239
5    Tuesday          2973
6  Wednesday          3024

# Month Trend for Total Orders

In [21]:
# Convert to datetime (if not already)
# df['order_date'] = pd.to_datetime(df['order_date'])

# Extract month name and count distinct orders
result = (
    df.groupby(df['order_date'].dt.month_name())['order_id']
      .nunique()
#       .reset_index(name='total_orders')
#       .rename(columns={'order_date': 'order_month'})
)

print(result)

order_date
April        1799
August       1841
December     1680
February     1685
January      1845
July         1935
June         1773
March        1840
May          1853
November     1792
October      1646
September    1661
Name: order_id, dtype: int64

# % of Sales by Pizza Category

In [38]:
df.groupby('pizza_category')['total_price'].sum()

pizza_category
Chicken    195919.50
Classic    220053.10
Supreme    208197.00
Veggie     193690.45
Name: total_price, dtype: float64

In [39]:
# Total revenue (for percentage calculation)
total_revenue = df['total_price'].sum()

# Group by pizza_category
result = (
    df.groupby('pizza_category')['total_price']
      .sum()
      .reset_index(name='total_revenue')
)

# Calculate percentage
result['PCT'] = round((result['total_revenue'] * 100) / total_revenue, 2)

# Round total_revenue to 2 decimal places
result['total_revenue'] = result['total_revenue'].round(2)

print(result)

  pizza_category  total_revenue    PCT
0        Chicken      195919.50  23.96
1        Classic      220053.10  26.91
2        Supreme      208197.00  25.46
3         Veggie      193690.45  23.68

# % of Sales by Pizza Size

In [23]:
# Total revenue (for percentage calculation)
total_revenue = df['total_price'].sum()

# Group by pizza_category
result = (
    df.groupby('pizza_size')['total_price']
      .sum()
      .reset_index(name='total_revenue')
)

# Calculate percentage
result['PCT'] = round((result['total_revenue'] * 100) / total_revenue, 2)

# Round total_revenue to 2 decimal places
result['total_revenue'] = result['total_revenue'].round(2)

print(result)

  pizza_size  total_revenue    PCT
0          L      375318.70  45.89
1          M      249382.25  30.49
2          S      178076.50  21.77
3         XL       14076.00   1.72
4        XXL        1006.60   0.12

# Top 5 Pizzas by Revenue

In [69]:
result = (
    df.groupby('pizza_name')['total_price']
      .sum()
      .reset_index(name='Total_Revenue')
      .sort_values(by='Total_Revenue', ascending=False)
      .head(5)
)

print(result)

                      pizza_name  Total_Revenue
30        The Thai Chicken Pizza       43434.25
0     The Barbecue Chicken Pizza       42768.00
4   The California Chicken Pizza       41409.50
7       The Classic Deluxe Pizza       38180.50
26       The Spicy Italian Pizza       34831.25